<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Adjudge.Sample.OpenAI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Adjudge/Adjudge.csproj" />
    <ProjectReference Include="../../src/Adjudge.OpenAI/Adjudge.OpenAI.csproj" />
  </ItemGroup>

</Project>
